name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          
      - name: Deploy to EC2 via AWS SSM
        run: |
          aws ssm send-command \
            --instance-ids "3.110.165.155" \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[
              'cd ~/nextjs-app',
              'git pull',
              'sudo docker stop nextjs-container || true',
              'sudo docker rm nextjs-container || true',
              'sudo docker build -t nextjs-app .',
              'sudo docker run -d -p 4000:4000 --name nextjs-container nextjs-app'
            ]"
